trying to fix prelink issues

diff --git a/check_package_checksum b/check_package_checksum
--- a/check_package_checksum
+++ b/check_package_checksum
@@ -200,15 +200,18 @@ checksum () {
       local package_checksum=$(rpm -ql --dump ${package_name} | egrep "^${file_path} " | awk '{print $4}')
 
       if [ ${prelink_enabled} == "true" ]; then
+        # This works
         local in_prelink_cache=$(prelink -p | egrep "^${file_path}:|^${file_path} ")
         if [[ ${in_prelink_cache} =~ not.prelinkable ]]; then
           local prelink_match="not prelinkable"
           local file_checksum=$( ${pkgmgr_digest} ${file_path} | awk '{print $1}')
 
         elif [[ ${in_prelink_cache} =~ ^${file_path}:$ ]]; then
+          # This fails...
           local prelink_match="true"
           local file_checksum=$(prelink -y ${file_path} 2>/dev/null | ${pkgmgr_digest} | awk '{print $1}'; echo ${PIPESTATUS[@]}; exit ${PIPESTATUS[0]})
-          local status=${?}
+          echo "file_checksum=$(prelink -y ${file_path} 2>/dev/null | ${pkgmgr_digest} | awk '{print $1}'; echo ${PIPESTATUS[@]}; exit ${PIPESTATUS[0]})"
+          status=${?}
           echo "status = ${status} - ?? - prelink_match=true"
           if [ ${status} -ne 0 ]; then
            prelink_status=$(prelink -y ${file_path} 1>/dev/null 2>&1)
@@ -216,6 +219,7 @@ checksum () {
           fi
 
         else
+          # This works!
           local prelink_match="false"
           # prelink -u ${file_path}
           # prelink -f ${file_path}
@@ -223,15 +227,15 @@ checksum () {
           local file_checksum_clean=$(${pkgmgr_digest} ${file_path} | awk '{print $1}')
           local file_checksum_prelink=$(prelink -y ${file_path} 2>/dev/null | ${pkgmgr_digest} | awk '{print $1}'; exit ${PIPESTATUS[0]})
           local status=${?}
-          echo " status = ${status}"
+          # echo " status = ${status}"
           if [ ${status} -ne 0 ]; then
             local prelink_status=$(prelink -y ${file_path} 1>/dev/null 2>&1)
           fi
 
-          echo "file                  : ${file_path}"
-          echo "package_checksum (s)  : ${package_checksum}"
-          echo "file_checksum_clean   : ${file_checksum_clean}"
-          echo "file_checksum_prelink : ${file_checksum_prelink}"
+          #echo "file                  : ${file_path}"
+          #echo "package_checksum (s)  : ${package_checksum}"
+          #echo "file_checksum_clean   : ${file_checksum_clean}"
+          #echo "file_checksum_prelink : ${file_checksum_prelink}"
 
           if [ "${package_checksum}" == "${file_checksum_clean}" ]; then
             local file_checksum=${file_checksum_clean}
